# Generated by Django 3.1.5 on 2021-01-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(help_text='Unique ID for this employee', primary_key=True, serialize=False)),
                ('surnname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('day_off1', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('day_off2', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('regular_login', models.TimeField(max_length=50)),
                ('regular_logout', models.TimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.employee')),
            ],
        ),
    ]
